version: '3.8'

services:
  teamspeak-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamspeak-mcp:latest
    container_name: teamspeak-mcp
    restart: unless-stopped

    ports:
      - "8000:8000"  # MCP port
    
    # TeamSpeak environment variables
    # Modify these values or use a .env file
    environment:
      - TEAMSPEAK_HOST=${TEAMSPEAK_HOST:-your-server.example.com}
      - TEAMSPEAK_PORT=${TEAMSPEAK_PORT:-10011}
      - TEAMSPEAK_USER=${TEAMSPEAK_USER:-serveradmin}
      - TEAMSPEAK_PASSWORD=${TEAMSPEAK_PASSWORD}
      - TEAMSPEAK_SERVER_ID=${TEAMSPEAK_SERVER_ID:-1}
      - MCP_MODE=${MCP_MODE:-streamable-http}
    
    # Alternative: use a .env file
    # env_file:
    #   - .env
    
    # Keep stdin open for MCP
    stdin_open: true
    tty: true
    
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels for Docker Swarm or organization
    labels:
      - "traefik.enable=false"
      - "com.teamspeak-mcp.description=MCP Server for TeamSpeak"
      - "com.teamspeak-mcp.version=1.0.0"

  # Optional service for testing
  teamspeak-mcp-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamspeak-mcp:latest
    container_name: teamspeak-mcp-test
    command: ["python", "test_mcp.py"]
    environment:
      - TEAMSPEAK_HOST=${TEAMSPEAK_HOST:-your-server.example.com}
      - TEAMSPEAK_PORT=${TEAMSPEAK_PORT:-10011}
      - TEAMSPEAK_USER=${TEAMSPEAK_USER:-serveradmin}
      - TEAMSPEAK_PASSWORD=${TEAMSPEAK_PASSWORD}
      - TEAMSPEAK_SERVER_ID=${TEAMSPEAK_SERVER_ID:-1}
    profiles:
      - test
    depends_on:
      - teamspeak-mcp 